{% set name = "trimesh" %}
{% set version = "3.6.30" %}
{% set sha256 = "1e8202191d34b46c3bbe4bf3bf6466e8748d4d96cc623f2c7195fd09ee79e962" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
  run_constrained:
    - scikit-image
    - msgpack-python
    - requests
    - pycollada
    - shapely
    - colorlog
    - meshio
    - setuptools
    - sympy
    - jsonschema
    - lxml
    - xxhash
    - rtree
    - pyglet
    - triangle
    - psutil
    - networkx
    - scipy
    - pillow
    - chardet

test:
  commands:
    - python -c "import trimesh"

about:
  home: https://github.com/mikedh/trimesh
  license: MIT

  # We can remove LICENSE.md from
  # the recipe when it is included
  # in the trimesh source dist:
  #
  # https://github.com/mikedh/trimesh/pull/176
  license_file: LICENSE.md
  summary: Import, export, process, analyze and view triangular meshes.
  dev_url: https://github.com/mikedh/trimesh

extra:
  recipe-maintainers:
    - mikedh
    - pauldmccarthy
